Main/urls.py
from django.urls import path

from . import views

app_name = "Main"

urlpatterns = [
    path("", views.index, name='home'),
    path("about", views.about, name='about'),
    path("contact", views.contact, name='contact'),


]

blog/urls.py
from django.urls import path

from . import views

from blog.feeds import LatestEntriesFeed

app_name='blog'

urlpatterns = [
    path("",views.home,name='home'),
    path("<int:id>",views.single_blog,name='blog-single'),
    path("category/<int:id>",views.home,name='category-filter'),
    path("tags/<str:tag_name>",views.home,name='tag'),
    path("Search",views.search,name='search'),
    path("rss/feed/", LatestEntriesFeed()),
    path('subscribe/', views.subscribe, name='subscribe'),

]

travelo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from Main.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    "static": StaticViewSitemap,
    "BlogSitemap": BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('blog/', include('blog.urls')),
    path('registration/', include('accounts.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.urls import reverse
from taggit.managers import TaggableManager


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date']
    def __str__(self):
        return self.name

class Category(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    image =models.ImageField(upload_to="blog/",default="blog/default.jpg")
    category=models.ManyToManyField(Category)
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_time=models.DateTimeField(auto_now=True)
    tags=TaggableManager()
    login_requier=models.BooleanField(default=False)


    class Meta:
        ordering=['-created_date']
        verbose_name='Post'
        verbose_name_plural='Posts'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return  reverse("blog:blog-single",kwargs={"id":self.id})

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=235)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    approved=models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name





class Newsletter(models.Model):
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

blog/forms.py
from  django import forms
from blog.models import Comment,Newsletter
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields =['post','name','email','subject', 'message']



class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ['email']

blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Post, Comment
from django.utils import timezone
from blog.forms import CommentForm, NewsletterForm
from django.contrib import messages


# Create your views here.

def home(request, id=None, tag_name=None):
    posts = Post.objects.filter(status=1, published_date__lte=timezone.now())
    if id:
        posts = posts.filter(category__id=id)
    if tag_name:
        posts = posts.filter(tags__name=tag_name)

        print(tag_name)
        print(posts)

    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"posts":  page_obj}
    return render(request, 'Blog/blog.html', context)


def single_blog(request, id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Submit Succsesfully")
        else:
            messages.add_message(request, messages.ERROR, "Not Succsesfully")

    post = get_object_or_404(Post, pk=id, status=1, published_date__lte=timezone.now())
    if post.login_requier == False:
        next_post = Post.objects.filter(id__gt=post.id, status=1, published_date__lte=timezone.now()).order_by('id').first()
        previous_post = Post.objects.filter(id__lt=post.id, status=1, published_date__lte=timezone.now()).order_by('id').first()
        post.counted_views += 1
        post.save()
        comments = Comment.objects.filter(post=post.id, approved=True).order_by("-created_date")
        form = CommentForm()
        context = {'post': post,
                   "next_post": next_post,
                   "previous_post": previous_post,
                   "comments": comments,
                   "form": form}
        return render(request, 'Blog/single-blog.html', context)
    elif request.user.is_authenticated:
        next_post = Post.objects.filter(id__gt=post.id, status=1, published_date__lte=timezone.now()).order_by('id').first()
        previous_post = Post.objects.filter(id__lt=post.id, status=1, published_date__lte=timezone.now()).order_by('id').first()
        post.counted_views += 1
        post.save()
        comments = Comment.objects.filter(post=post.id, approved=True).order_by("-created_date")
        form = CommentForm()
        context = {'post': post,
                   "next_post": next_post,
                   "previous_post": previous_post,
                   "comments": comments,
                   "form": form}
        return render(request, 'Blog/single-blog.html', context)
    else:
        return redirect("accounts:login")


def search(request):
    posts = Post.objects.filter(status=1)
    if request.method == "GET":
        if s := request.GET.get("s"):
            posts = posts.filter(content__contains=s)
    context = {"posts": posts}
    return render(request, 'Blog/blog.html', context)




def subscribe(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have successfully subscribed to the newsletter!')
            return redirect('Main:home')
        else:
            messages.add_message(request, messages.ERROR, "Not Succsesfully")
            return redirect('Main:home')

    else:
        form = NewsletterForm()
        return render(request, 'Blog/blog.html')

templates/Blog/Module/author.html
{% load static %}
<div class="navigation-top">
    <div class="d-sm-flex justify-content-between text-center">
        <p class="like-info"><span class="align-middle"><i class="fa fa-heart"></i></span> Lily and
            4
            people like this</p>
        <div class="col-sm-4 text-center my-2 my-sm-0">

        </div>
        <ul class="social-icons">
            <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-behance"></i></a></li>
        </ul>
    </div>
    <div class="navigation-area">
        <div class="row">

            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                {% if previous_post %}
                    <div class="thumb">
                        <a href="{% url 'blog:blog-single' id=previous_post.id %}">
                            <img class="img-fluid" src="{% static 'img/post/preview.png' %}" alt>
                        </a>
                    </div>
                    <div class="arrow">
                        <a href="{% url 'blog:blog-single' id=previous_post.id %}">
                            <span class="lnr text-white ti-arrow-left"></span>
                        </a>
                    </div>
                    <div class="detials">
                        <p>Prev Post</p>
                        <a href="{% url 'blog:blog-single' id=previous_post.id %}">
                            <h4>{{ previous_post.title }}</h4>
                        </a>
                    </div>
                {% endif %}
            </div>
            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                {% if next_post %}

                    <div class="detials">
                        <p>Next Post</p>
                        <a href="{% url 'blog:blog-single' id=next_post.id %}">
                            <h4>{{ next_post.title }}</h4>
                        </a>
                    </div>
                    <div class="arrow">
                        <a href="{% url 'blog:blog-single' id=next_post.id %}">
                            <span class="lnr text-white ti-arrow-right"></span>
                        </a>
                    </div>
                    <div class="thumb">
                        <a href="#">
                            <img class="img-fluid" src="{% static 'img/post/next.png' %}" alt>
                        </a>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>
<div class="blog-author">
    <div class="media align-items-center">
        <img src="{% static 'img/blog/author.png' %}" alt>
        <div class="media-body">
            <a href="#">
                <h4>Harvard milan</h4>
            </a>
            <p>Second divided from form fish beast made. Every of seas all gathered use saying
                you're,
                he
                our dominion twon Second divided from</p>
        </div>
    </div>
</div>

templates/Blog/Module/category.html
{% load static %}
{% load blog_tags %}
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">Category</h4>
    <ul class="list cat-list">
        {% for name,count in value.items %}
            <li>
                <a href="{% url 'blog:category-filter' id=name.id %}" class="d-flex">
                    <p>{{ name }}</p>

                    <p>({{ count }})</p>
                </a>
            </li>
        {% endfor %}
    </ul>
</aside>

templates/Blog/Module/comment area and form.html
{% load static %}
{% load humanize %}

<div class="comments-area">

    <h4>{{ comments|length }} Comments</h4>
    {% for comment in comments %}
        <div class="comment-list">
            <div class="single-comment justify-content-between d-flex">
                <div class="user justify-content-between d-flex">
                    <div class="thumb">
                        <img src="{% static 'img/comment/comment_1.png' %}" alt>
                    </div>
                    <div class="desc">
                        <p class="comment">
                            {{ comment.message }}
                        </p>
                        <div class="d-flex justify-content-between">
                            <div class="d-flex align-items-center">
                                <h5>
                                    <a href="#">{{ comment.name }}</a>
                                </h5>
                                <p class="date">{{ comment.created_date|naturalday }} </p>
                            </div>
                            <div class="reply-btn">
                                <a href="#" class="btn-reply text-uppercase">reply</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <p1> No Comments</p1>
        </div>
    {% endfor %}
<div class="comment-form">
    <h4>Leave a Reply</h4>
    <form class="form-contact comment_form" method="post" action="{% url "blog:blog-single" id=post.id %}"
          id="commentForm">
        {% csrf_token %}
        <div class="row">
            <input class="form-control" name="post" id="website" type="hidden" value="{{ post.id }}">
            <div class="col-12">
                <div class="form-group">
                    <input class="form-control" name="subject" id="website" type="text" placeholder="subject">
                </div>
            </div>
            <div class="col-12">
                <div class="form-group">
                    <textarea class="form-control w-100" name="message" id="comment" cols="30" rows="9"
                              placeholder="Write Comment"></textarea>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                </div>
            </div>
            <div class="col-12">
                <!-- CAPTCHA Field -->
                <div class="form-group">
                    {{ form.captcha.errors }} <!-- To show CAPTCHA errors if there are any -->
                    {{ form.captcha }}         <!-- This renders the CAPTCHA field -->
                </div>
            </div>

        </div>
        <div class="form-group">
            <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message
            </button>
        </div>
    </form>

</div>

templates/Blog/Module/instagram_feeds.html
{% load static %}
<aside class="single_sidebar_widget instagram_feeds">
    <h4 class="widget_title">Instagram Feeds</h4>
    <ul class="instagram_row flex-wrap">
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_5.png' %}" alt>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_6.png' %}" alt>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_7.png' %}" alt>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_8.png' %}" alt>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_9.png' %}" alt>
            </a>
        </li>
        <li>
            <a href="#">
                <img class="img-fluid" src="{% static 'img/post/post_10.png' %}" alt>
            </a>
        </li>
    </ul>
</aside>

templates/Blog/Module/newsletter_widget.html
{% load static %}
<aside class="single_sidebar_widget newsletter_widget">
    <h4 class="widget_title">Newsletter</h4>
    <form action="{% url 'blog:subscribe' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input name="email" type="email" class="form-control" onfocus="this.placeholder = ''"
                   onblur="this.placeholder = 'Enter email'" placeholder="Enter email" required>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                type="submit">
            Subscribe
        </button>
    </form>
</aside>

templates/Blog/Module/popular_post.html
{% load static %}
{% load blog_tags %}
{% load humanize %}

<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Latest Post</h3>
    {% for post in posts %}
        <div class="media post_item">
            <img style="max-width: 100px" src="{{ post.image.url }}" alt="post">
            <div class="media-body">
                <a href="{% url "blog:blog-single" id=post.id %}">
                    <h3>{{ post.title }}</h3>
                </a>
                <p>{{ post.published_date|date:"d M Y" }}</p>
                <p>{{ post.published_date|naturaltime }}</p>
            </div>
        </div>
    {% endfor %}
</aside>

templates/Blog/Module/search.html
{% load static %}
<aside class="single_sidebar_widget search_widget">
    <form action="{% url 'blog:search' %}" method="get">
        <div class="form-group">
            <div class="input-group mb-3">
                <input name="s" type="text" class="form-control" placeholder="Search Keyword"
                       onfocus="this.placeholder = ''"
                       onblur="this.placeholder = 'Search Keyword'">
                <div class="input-group-append">
                    <button class="btn" type="button"><i class="ti-search"></i></button>
                </div>
            </div>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                type="submit">
            Search
        </button>
    </form>
</aside>

templates/Blog/Module/tag.html
{% load static %}
<aside class="single_sidebar_widget tag_cloud_widget">
    <h4 class="widget_title">Tag Clouds</h4>
    <ul class="list">
        {% for tag in post.tags.all %}
            <li>
                <a href="{% url "blog:tag" tag_name=tag.name %}" }>{{ tag.name }}</a>
            </li>
        {% endfor %}
    </ul>
</aside>